/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7db1e953-c159-48e9-b636-f45584767502",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jxWpu566g",
    "aws_user_pools_web_client_id": "5eu0ici8bpe0ojp2pscsao98us",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://poolngk6cjc5dkhld5xfqgjnbu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-effyyuoucjc6vekqbkusxpab54"
};


export default awsmobile;
